# Generated by Django 2.2.3 on 2019-08-08 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aanisite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='name',
            field=models.CharField(max_length=63),
        ),
        migrations.AlterField(
            model_name='product',
            name='generic_name',
            field=models.CharField(max_length=63),
        ),
        migrations.AlterField(
            model_name='product',
            name='trade_name',
            field=models.CharField(max_length=63),
        ),
        migrations.AlterField(
            model_name='theraputiccategory',
            name='name',
            field=models.CharField(max_length=63),
        ),
    ]
