# Generated by Django 2.2.5 on 2020-06-12 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Aanisite', '0004_experiments_packagingmaterialsspecifications_rawmaterialandexcipientspecifications_specificationsofd'),
    ]

    operations = [
        migrations.AddField(
            model_name='ttmtcontract',
            name='experiments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Aanisite.Experiments'),
        ),
        migrations.AddField(
            model_name='ttmtcontract',
            name='packaging_materials_specifications',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Aanisite.PackagingMaterialsSpecifications'),
        ),
        migrations.AddField(
            model_name='ttmtcontract',
            name='raw_material_and_excipient_specifications',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Aanisite.RawMaterialAndExcipientSpecifications'),
        ),
        migrations.AddField(
            model_name='ttmtcontract',
            name='specifications_of_devices_and_equipment_used_in_production',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Aanisite.SpecificationsOfDevicesAndEquipmentUsedInProduction'),
        ),
    ]
